# Generated by Django 5.1.6 on 2025-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('sports', 'Sports'), ('esports', 'E-Sports')], max_length=10)),
                ('sports_game', models.CharField(blank=True, max_length=50, null=True)),
                ('esports_game', models.CharField(blank=True, max_length=50, null=True)),
                ('tournament_name', models.CharField(max_length=100)),
                ('tournament_level', models.CharField(choices=[('district', 'District Level'), ('state', 'State Level'), ('national', 'National Level'), ('school', 'School/University Level')], max_length=20)),
                ('head_organizer', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('venue_name', models.CharField(max_length=100)),
                ('num_teams', models.PositiveIntegerField()),
                ('num_individuals', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='tournament_posters/')),
                ('last_year_winner', models.ImageField(upload_to='tournament_winners/')),
                ('ground_image', models.ImageField(upload_to='ground_images/')),
                ('tournament_video', models.FileField(upload_to='tournament_videos/')),
                ('stay_living', models.CharField(blank=True, max_length=50, null=True)),
                ('food', models.CharField(blank=True, max_length=50, null=True)),
                ('traveling_charge', models.CharField(blank=True, max_length=50, null=True)),
                ('team_dress', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_fee', models.BooleanField(default=False)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('age_limit', models.BooleanField(default=False)),
                ('age_category', models.CharField(blank=True, max_length=20, null=True)),
                ('team_entry', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
