# Generated by Django 5.1.6 on 2025-04-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='head_organizer',
            new_name='organizer_name',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='fee_amount',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='food',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='last_year_winner',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='stay_living',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='traveling_charge',
        ),
        migrations.AddField(
            model_name='tournament',
            name='entry_fee_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='food_facility',
            field=models.CharField(default='not_provided', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='stay_facility',
            field=models.CharField(default='match_time', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_poster',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_posters/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='travel_charge',
            field=models.CharField(default='not_provided', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner_runner_image',
            field=models.ImageField(blank=True, null=True, upload_to='winner_runner_images/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='age_category',
            field=models.CharField(blank=True, choices=[('under_14', 'Under 14'), ('under_16', 'Under 16'), ('under_19', 'Under 19'), ('under_23', 'Under 23')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='age_limit',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='entry_fee',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='esports_game',
            field=models.CharField(blank=True, choices=[('counter_strike', 'Counter-Strike'), ('dota_2', 'Dota 2'), ('league_of_legends', 'League of Legends'), ('fortnite', 'Fortnite'), ('pubg', 'PUBG'), ('valorant', 'Valorant'), ('fifa', 'FIFA'), ('call_of_duty', 'Call of Duty')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game_type',
            field=models.CharField(choices=[('sports', 'Sports'), ('esports', 'E-Sports')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ground_image',
            field=models.ImageField(blank=True, null=True, upload_to='ground_images/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_individuals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_teams',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sports_game',
            field=models.CharField(blank=True, choices=[('cricket', 'Cricket'), ('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('hockey', 'Hockey'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('chess', 'Chess')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='team_dress',
            field=models.CharField(default='not_provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='team_entry',
            field=models.CharField(choices=[('direct', 'Direct Entry'), ('trial', 'On the trial basis')], default='direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_level',
            field=models.CharField(choices=[('district', 'District level'), ('state', 'State level'), ('national', 'National level'), ('school', 'School or University level')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_video',
            field=models.FileField(blank=True, null=True, upload_to='tournament_videos/'),
        ),
    ]
