# Generated by Django 5.1.6 on 2025-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_rename_head_organizer_tournament_organizer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='prize_pool',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
