# Generated by Django 5.1.6 on 2025-04-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_other_prizes_tournament_player_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='other_prizes',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='player_match',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='player_tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='prize_pool_available',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='runner_prize',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='winner_prize',
        ),
    ]
