# Generated by Django 5.1.6 on 2025-04-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_remove_tournament_other_prizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='gender_category',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], default='mixed', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='other_prizes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='participant_type',
            field=models.CharField(blank=True, choices=[('team', 'Team'), ('individual', 'Individual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_match',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_tournament',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules_document',
            field=models.FileField(blank=True, null=True, upload_to='rules_documents/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='runner_prize',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner_prize',
            field=models.TextField(blank=True, null=True),
        ),
    ]
