# Generated by Django 5.1.6 on 2025-04-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_gender_category_tournament_other_prizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool_available',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='gender_category',
            field=models.CharField(choices=[('mixed', 'Mixed'), ('male', 'Male'), ('female', 'Female')], default='mixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_individuals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_teams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participant_type',
            field=models.CharField(blank=True, choices=[('teams', 'Teams'), ('individuals', 'Individuals')], max_length=20, null=True),
        ),
    ]
