# Generated by Django 5.1.6 on 2025-05-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='district',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='state',
        ),
        migrations.AddField(
            model_name='tournament',
            name='district_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='district_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='state_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='state_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
