# Generated by Django 5.1.6 on 2025-04-27 23:37

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(blank=True, default='default_images/background.jpg', null=True, upload_to=profiles.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_images/profile.jpg', null=True, upload_to=profiles.models.user_directory_path),
        ),
    ]
